### ISSUE TITLE
[Feature Request] json libraries(currently gson) used in datakernel codec should be swappable with other libraries 

### ISSUE THREAD

**Issue by KrishnaST** [softindex/datakernel#16]

**Comment by necauqua** [comment]
Hi @KrishnaST!

Codecs themselves do not depend on the backend, so you can freely implement `StructuredInput` and `StructuredOutput` for any of your favorite data types or formats - using any preferred libraries, and then use your codecs with them.

Currently DataKernel contains two such implementations - one is a simple raw binary position-dependent format ([BinaryUtils](https://github.com/softindex/datakernel/blob/master/core-codec/src/main/java/io/datakernel/codec/binary/BinaryUtils.java)) and another is a subset of JSON that uses gson's JsonReader/JsonWriter ([JsonUtils](https://github.com/softindex/datakernel/blob/master/core-codec/src/main/java/io/datakernel/codec/json/JsonUtils.java)).

Another option is not to use the codecs altogether - just use your library of choiсe directly where you need it, because DataKernel is not as tightly coupled as other frameworks and allows such usage with little effort.

**Comment by KrishnaST** [comment]
Thanks.

**Comment by necauqua** [comment]
Also we've removed the datakernel-codec optional dependency from datakernel-http entirely.

HTTP response method `.withJson(StructuredCodec<T>, T object)` was replaced with `.withJson(String)` which is now a shortcut that just adds a json content-type similar to `withHtml` and `.withPlainText` methods.

**Comment by OneCricketeer** [comment]
> another is a subset of JSON that uses gson's JsonReader/JsonWriter (JsonUtils).

I don't suppose there's a Jackson databind implementation out there? Or I've just not looked long enough 😊
