### ISSUE TITLE
When there are too many http requests, subsequent requests will time out directly

### ISSUE THREAD

**Issue by zzl221000** [softindex/datakernel#18]
Use AysncHttpClient in EventLoop to create a large number of requests, if the given timeout is 10 seconds, after 10 seconds, those requests that do not rotate will also time out

**Comment by eduard-vasinskyi** [comment]
Hello, @zzl221000. Our HTTP client is used in production in a high load environment for handling tens of thousands of concurrent requests efficiently.

Could you please provide an example that illustrates the problem with timed out requests, so we could help?

**Comment by zzl221000** [comment]
Hey, @eduard-vasinskyi 
I am using eventloop in disruptor. there are a lot of JDBC operations in the code. These tasks are submitted to eventloop
```
AsyncHttpClient asyncHttpClient=AsyncHttpClient.create(eventloop).withConnectTimeout(Duration.ofSeconds(10)).withReadWriteTimeout(Duration.ofSeconds(10)).withKeepAliveTimeout(Duration.ofSeconds(10));
```

eventloop submit follow tasks:

```
List<Promise> promises=list.stream().map(use asyncHttpClient requst).collection(toList());
Promises.ofList(promises).whenResult(submit other task to eventloop,it call a lot of JDBC api)
```

**Comment by eduard-vasinskyi** [comment]
Hello, @zzl221000.
Unfortunately, it is not yet clear how your application works. Could you please provide a minimalistic example that demonstrates how JDBC tasks are submitted to the Eventloop? Use stubs instead of an actual JDBC API.

However, we might guess that the problem is that you are submitting blocking tasks to the Eventloop which goes against principles of high-performance non-blocking architecture. Blocking tasks will delay the execution of HTTP requests as the HTTP client will wait for JDBC operations to finish. That's why you should never submit any blocking I/O operations to Eventloop and use an external executor for blocking I/O.

We also recommend you to not run Eventloop from within disruptor, but use a separate thread instead. The performance of the HTTP client is high enough that it won't be a bottleneck in your application. 

There are 2 options for you (assuming that you run Eventloop in a separate thread):
 - Submit all of your HTTP requests to the Eventloop by calling `eventloop.submit()`. You should pass a supplier of some promise to the method. A `CompletablaFutur`e will be returned that you can use in caller thread for further JDBC tasks. However, you can not return a promise of HttpResponse here, you should parse HttpResponse into some DTO class, based on your business logic.
- Another option is to delegate further processing to some Executor. For example: 
```java
Promises.ofList(promises)
     .whenResult(result -> executor.execute(doSomethingWithResult(result))
```

Unfortunately, we might only guess if this is the reason for HTTP requests timing out, as we need a more detailed example so we are able to help you out, but it looks like the problem is caused by blocking I/O.

**Comment by zzl221000** [comment]
Thanks @eduard-vasinskyi
